// Re-export types used by the server (mirrors src/types/run.ts for server use)
export type {
  Run,
  RunStatus,
  RunVersion,
  EnvironmentConfig,
  SourceFile,
  SourceTable,
  SourceColumn,
  ForeignKeyHint,
  AnalysisResult,
  DataverseSchemaProposal,
  ProposedTable,
  ProposedField,
  ProposedRelationship,
  SourceToDestMapping,
  NativeTableMapping,
  Risk,
  UserEdit,
  Approval,
  Job,
  JobStep,
  LogEntry,
} from '../src/types/run';
